OK_FORMAT = True

test = {   'name': 'q1.4.2',
    'points': 0.5,
    'suites': [   {   'cases': [   {   'code': '>>> value_list = [1, 2, 3]\n>>> isinstance(cv_142(value_list), np.ndarray)\nTrue',
                                       'failure_message': 'Your function does not return a numpy array.',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0},
                                   {   'code': '>>> value_list = [1, 2, 3]\n>>> cv_142(value_list).shape == (3, 1)\nTrue',
                                       'failure_message': 'Your function does not return a column vector of the correct shape.',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0},
                                   {   'code': '>>> value_list = [1, 2, 3]\n>>> cv_142(value_list).tolist() == [[1], [2], [3]]\nTrue',
                                       'failure_message': 'Your function does not return the correct column vector.',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0},
                                   {   'code': ">>> import inspect\n>>> cv_142_str = inspect.getsource(cv_142)\n>>> 'for' not in cv_142_str and 'while' not in cv_142_str\nTrue",
                                       'failure_message': "Your function contains a loop. Please remove all for/while loops. (If have comments containing the words 'for' or 'while', please remove "
                                                          'those comments as well.)',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
