OK_FORMAT = True

test = {   'name': 'q1.4.1',
    'points': 0.5,
    'suites': [   {   'cases': [   {   'code': '>>> value_list = [1, 2, 3]\n>>> isinstance(rv_141(value_list), np.ndarray)\nTrue',
                                       'failure_message': 'Your function does not return a numpy array.',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0},
                                   {   'code': '>>> value_list = [1, 2, 3]\n>>> rv_141(value_list).shape == (1, 3)\nTrue',
                                       'failure_message': 'Your function does not return a row vector of the correct shape.',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0},
                                   {   'code': '>>> value_list = [1, 2, 3]\n>>> rv_141(value_list).tolist() == [[1, 2, 3]]\nTrue',
                                       'failure_message': 'Your function does not return the correct row vector.',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0},
                                   {   'code': ">>> rv_141_str = inspect.getsource(rv_141)\n>>> 'for' not in rv_141_str and 'while' not in rv_141_str\nTrue",
                                       'failure_message': "Your function contains a loop. Please remove all for/while loops. (If have comments containing the words 'for' or 'while', please remove "
                                                          'those comments as well.)',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
