OK_FORMAT = True

test = {   'name': 'q2.4',
    'points': 4,
    'suites': [   {   'cases': [   {   'code': '>>> Y = np.array([[1], [2], [3]])\n>>> Y_hat = np.array([[1.1], [2.1], [3.1]])\n>>> isinstance(mse_24(Y, Y_hat), np.ndarray)\nTrue',
                                       'failure_message': 'Your function does not return a numpy array.',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0},
                                   {   'code': '>>> Y = np.array([[1], [2], [3]])\n>>> Y_hat = np.array([[1.1], [2.1], [3.1]])\n>>> mse_24(Y, Y_hat).shape == (1, 1)\nTrue',
                                       'failure_message': 'Your function does not return a 1x1 numpy array.',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0},
                                   {   'code': '>>> Y = np.array([[1], [2], [3]])\n>>> Y_hat = np.array([[1.1], [2.1], [3.1]])\n>>> np.allclose(mse_24(Y, Y_hat), np.array([[0.01]]))\nTrue',
                                       'failure_message': 'Your function does not return the correct value.',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0},
                                   {   'code': ">>> mse_24_str = inspect.getsource(mse_24)\n>>> 'for' not in mse_24_str and 'while' not in mse_24_str\nTrue",
                                       'failure_message': "Your function contains a loop. Please remove all for/while loops. (If have comments containing the words 'for' or 'while', please remove "
                                                          'those comments as well.)',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
